config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  get '/pages/home' => 'pages#home'
  get '/pages/:page' => 'pages#show', as: :page
  get '/preferences' => 'preferences#edit'

  resources :allergies, only: [:new, :create]
  resources :likes, only: [:new, :create]
  resources :dislikes, only: [:new, :create]
  resources :users, only: [:show, :edit, :update]
  resources :orders do
    resources :payments, only: [:new, :create]
  end
  get '/smoothies/:order_id/configure', to: 'orders#configure', as: :order_configure
  post '/orders/:order_id/add_items', to: 'orders#add_items', as: :order_add_items
  get '/orders/:order_id/confirmation', to: 'orders#confirmation', as: :order_confirmation
  post '/orders/:order_id/delivery_info', to: 'orders#delivery_info', as: :order_delivery_info
  get '/smoothies/choose-amount' => 'orders#choose_amount'
  resources :smoothies, only: [:index, :show, :edit, :update]


    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  monetize :smoothies_price_cents
  monetize :total_smoothies_price_cents
  has_many :order_items, dependent: :destroy
  accepts_nested_attributes_for :order_items
  has_many :smoothies, through: :order_items

  validates :user_id, presence: true

  geocoded_by :delivery_address
  after_validation :geocode, if: :will_save_change_to_delivery_address?
  # validates :delivery_address, presence: true    Need lambda if order.confirmed
  # validates :delivery_date, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
    @order.build_order_items
  end

  def create
    @order = Order.new(user_id: current_user.id)
    smoothies_price_cents = 0
    smoothies_amount = params[:amount]
    case smoothies_amount
        when "7" then smoothies_price_cents = 650
        when "14" then smoothies_price_cents = 550
        when "21" then smoothies_price_cents = 450
        when "28 "then smoothies_price_cents = 400
    end
    @order.smoothies_amount = smoothies_amount
    @order.smoothies_price_cents = smoothies_price_cents
    @order.total_smoothies_price_cents = smoothies_price_cents * smoothies_amount.to_i
    if @order.save
      redirect_to order_configure_path(@order)
    else
      render :choose_amount
    end
  end

  def choose_amount
  end

  def configure
    @smoothies = Smoothie.all
    @order = Order.find(params[:order_id])
  end

  def add_items
    @order = Order.find(params[:order_id])
    order_item_params[:order_items].each do |smoothie, quantity|
      next unless quantity.present?
      smoothie_id = smoothie.gsub('smoothie_quantity', '')
      OrderItem.create(smoothie_quantity: quantity, order: @order, smoothie_id: smoothie_id)
    end
    redirect_to order_confirmation_path
  end

  def confirmation
    @order = Order.find(params[:order_id])
  end

  def delivery_info
    @order = Order.find(params[:order_id])
    @order.update(order_delivery_params)
    #   render order_confirmation_path(@order)
    # else
    #   flash.now[:alert] = 'Please check your address'
    # end
  end

  private

  def order_item_params
    params.require(:order).permit(order_items: {})
  end

  def order_delivery_params
    params.require(:order).permit(:smoothies_price_cents, :delivery_address, :delivery_date, :delivery_time_period)
  end
end

app/views/orders/choose_amount.html.erb
<div class="container">
  <h2 class="section__title" id="choose-amount">Choose Amount</h2>

  <div class="amount">

    <!-- <div class="amount__selected-info-top">
      You have selected:
    </div> -->

    <div id="amount__selected" class="amount__selected">
      7
    </div>

     <div id="price_amount__selected" class="price_amount__selected">
      €6.50 per Smoothie
    </div>

    <div class="amount__measure">
      <span>7</span>
      <span>14</span>
      <span>21</span>
      <span>28</span>
    </div>

    <div class="amount__bar">
      <%= simple_form_for Order.new, :url => orders_path, :method => :post do |f| %>
      <%= f.input :smoothies_amount, as: :range, label: false,
      input_html: { id:"amount",
       min:"7", max:"28", step:"7", value:7, name:"amount"} %>
      <%= f.submit'Choose smoothies', class: 'btn-center btn btn-lg btn-success smbt' %>
      <% end %>
    </div>

  </div>

  <%#= link_to 'Create Your Basket', orders_path(:smoothies_amount => "?smoothies_quantity"), method: :post, class: 'btn-center btn btn-lg btn-success' %>

</div>

<script>
  const amount = document.getElementById("amount");
  const selected_amount = document.getElementById("amount__selected");
  const price_amount_selected = document.getElementById("price_amount__selected");
  amount.addEventListener("change", (event) => {
      event.preventDefault();
      selected_amount.innerHTML = event.target.value;
      if (event.target.value === "7") {
        price_amount_selected.innerHTML = "€6.50 per Smoothie";
      } else if (event.target.value === "14") {
        price_amount_selected.innerHTML = "€5.50 per Smoothie";
      } else if (event.target.value === "21") {
        price_amount_selected.innerHTML = "€4.50 per Smoothie";
      } else {
        price_amount_selected.innerHTML = "€4.00 per Smoothie";
      }
  });

</script>

app/views/orders/configure.html.erb
<div class="configure">

  <div class="configure__sidebar">
    <div class="selected-smoothies">
      <div class="selected-smoothies__total">
        <h3>Your selection</h3>
        <div>You have selected
          <span id="selected-smoothies__total">0</span>
          of
          <span id="selected-smoothies__max"><%= @order.smoothies_amount %></span>
          smoothies
        </div>
      </div>
      <div id="upgrade-banner" class="text-danger hidden">
        Do you wan't to upgrade to a larger amount of Smoothies?
      </div>
      <div class="selected-smoothie__summary">
        <ul id="selected-smoothie-list" class="list-group">
        </ul>
      </div>
      <button id="order-submit" class="btn btn-success" type="button">Order</button>
    </div>
  </div>

  <div class="configure__content">
    <div class="container">
      <h2 class="section__title">Configure Your Basket</h2>
      <%= simple_form_for :order, url: order_add_items_path(@order) do |form| %>

      <div class="smoothies">
        <% @smoothies.each do |smoothie| %>

        <div class="smoothie">
          <img src="<%= smoothie.photo %>" alt="" width ="150" height="120">

          <%= form.simple_fields_for :order_items do |s| %>
          <h3><%=smoothie.name%></h3>

          <div class="smoothie__amount">
            <% key = "smoothie_quantity" + smoothie.id.to_s %>
            <%= s.input key.to_sym, selected: 0, collection: (0..7), label: "Quantity", required: false %>
          </div>
          <% end %>
          <div class="btn btn-default" id="sbtm" data-toggle="modal" data-target='<%= "#detox_description_#{smoothie.id}" %>'>Details</div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>



  <% @smoothies.each do |smoothie| %>
  <div class="modal fade" id='<%= "detox_description_#{smoothie.id}" %>' tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header ">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>

          <strong><h4 class="modal-title" id="exampleModalLabel"><%=smoothie.name%></h4></strong>
          <%= smoothie.description %>
        </div>
        <div class="modal-body">
          <div class="smoothie__ingredients">
            <h2 class="smoothie__ingredients__title">Ingredients</h2>
            <% smoothie.doses.each do |d| %>
            <div class="smoothie-dose__ingredient">
              <div class="smoothie-dose__details">
                <h4 class="ingredient__name">
                  <%= d.ingredient.name %> <%= d.value%><%= d.unit%>
                </h4>
                <div class="ingredient__details">
                  <%= d.ingredient.description || "#{d.ingredient.name} description coming soon..." %>
                </div>
              </div>
              <div class="ingredient__photo">
                <img src="<%= d.ingredient.photo %>" alt="" class="ingredient_photo_popup">
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
       <!--  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->

      </div>
    </div>
  </div>

</div>
<% end %>
<script>
  const maxSmoothies = <%= raw @order.smoothies_amount.to_json %>;
  const totalSmoothies = <%= raw @smoothies.all().to_json %>;
  const upgradeBanner = document.getElementById('upgrade-banner');
  let selectedSmoothies = {};
  totalSmoothies.forEach((smoothie, index) => {
    const totalSelectedSmoothies = document.getElementById(
      'selected-smoothies__total'
      );
    const smoothieAmount = document.getElementById(
      `order_order_items_smoothie_quantity${index + 1}`
      );
    smoothieAmount.addEventListener("change", (event) => {
      event.preventDefault();
      (event.target.value === '0')
      ? delete selectedSmoothies[smoothie.name]
      : selectedSmoothies[smoothie.name] = event.target.value;
      const selectedSmoothieList = document.getElementById(
        'selected-smoothie-list'
        );
      while (selectedSmoothieList.firstChild) {
        selectedSmoothieList.removeChild(selectedSmoothieList.firstChild);
      }
      Object.keys(selectedSmoothies).forEach(smoothieName => {
        const listItem = document.createElement('li');
        listItem.className = "list-group-item";
        listItem.innerHTML = `
          <span class="badge">
            ${selectedSmoothies[smoothieName]}
          </span>
          ${smoothieName}
        `;
        selectedSmoothieList.appendChild(listItem);
      });
      const countSelectedSmoothies = Object.values(selectedSmoothies).reduce((total, amount) => parseInt(total) + parseInt(amount));
      totalSelectedSmoothies.innerHTML = countSelectedSmoothies;
      if (countSelectedSmoothies > maxSmoothies) {
        totalSelectedSmoothies.classList.add('text-danger');
        totalSelectedSmoothies.classList.remove('text-success');
        upgradeBanner.classList.remove('hidden');
      } else {
        totalSelectedSmoothies.classList.add('text-success');
        totalSelectedSmoothies.classList.remove('text-danger');
        upgradeBanner.classList.add('hidden');
      }
    });
  });
 document.getElementById("order-submit").addEventListener("click", event => {
    console.log("hello")
    document.querySelector(".simple_form.order").submit()
  })
</script>

app/views/orders/confirmation.html.erb
<div class="container">
  <div class="row">

  <div class="basket col-sm-4">
    <div class='form confirmation-box'>
      <h3>Your Basket</h3>
      <% @order.order_items.each do |item| %>
      <% next if item.smoothie_quantity == 0 %>
        <% smoothie = Smoothie.find(item.smoothie_id) %>
        <p><%= item.smoothie_quantity %> <%= smoothie.name %></p>
      <% end %>
    </div>
  </div>

  <div class="checkout">
    <div class="delivery-info col-sm-4">
      <div class='form confirmation-box'>
        <div class="form-inputs">
          <h3>Delivery</h3>
          <%= simple_form_for :order, url: order_delivery_info_path(@order) do |f| %>
          <%= f.input :delivery_address, input_html: { autocomplete: "address" }, class: "form-control" %>
          <%= f.input :delivery_date, as: :string, input_html: {class: "datepicker"}, class: "form-control" %>
          <%= f.input :delivery_time_period,
               input_html: { class: "form-control" },
               collection: [
                [ '0', 'Please select your delivery time'],
                ['08:00-10:00', '08:00-10:00'],
                ['10:00-12:00', '10:00-12:00'],
                ['12:00-14:00', '12:00-14:00'],
                ['14:00-16:00', '14:00-16:00'],
                ['16:00-18:00', '16:00-18:00'],
                ['18:00-12:00', '18:00-20:00'],
              ],
              selected: 0,
              label_method: :second,
              value_method: :first
              %>

          <%#= f.input :delivery_date, as: :wday %>
        </div>
          <%= f.submit 'Confirm', class: 'btn btn-default', id: 'pay' %>
        <% end %>
      </div>
  </div>
    <div class="payment-info col-sm-4">
      <div class="form confirmation-box">
        <h3>Payment</h3>
        <div>
          <%= render 'payments/new'%>
        </div>
          <%#= link_to 'Pay',new_order_payment_path(@order) , class: "btn btn-default" %>
      </div>
    </div>

  </div>
  </div>
</div>

app/views/orders/old_configure.html.erb
<div class="configure">
  <div class="configure__sidebar">
    <div class="selected-smoothies">
      <div class="selected-smoothies__total">
        <h3>Your selection</h3>
        <div>You have selected
          <span id="selected-smoothies__total">0</span>
          of
          <span id="selected-smoothies__max"><%= @order.smoothies_amount %></span>
          smoothies
        </div>
      </div>
      <div id="upgrade-banner" class="text-danger hidden">
        Do you wan't to upgrade to a larger amount of Smoothies?
      </div>
      <div class="selected-smoothie__summary">
        <ul id="selected-smoothie-list" class="list-group">
        </ul>
      </div>
      <button id="order-submit" class="btn btn-success" type="button">Order</button>
    </div>
  </div>
  <div class="configure__content">
    <div class="container">
      <h1>Configure Your Basket</h1>
      <%= simple_form_for :order, url: order_add_items_path(@order) do |form| %>
      <div class="smoothies">
        <% @smoothies.each_with_index do |smoothie, index| %>
        <div class="smoothie">
          <img src="<%= smoothie.photo %>" alt="" width ="150" height="120">
          <%= form.simple_fields_for :order_items, remote: true do |s| %>
          <h3><%=smoothie.name%></h3>
            <% id = "order_order_items_smoothie_quantity#{index+1}" %>
            <div class="smoothie-quantity-plus">
                <button data-field-id= <%= id %>  class="quantity-increase btn btn-default" > + </button>
            </div>
            <div class="smoothie__amount">
              <% key = "smoothie_quantity" + smoothie.id.to_s %>
              <%= s.input key.to_sym, selected: 0, required: false, label: false,
              input_html: {id: id, value: 0} %>
            </div>
            <div class="smoothie-quantity-minus">
              <button data-field-id= <%= id %>  class="quantity-decrease"> - </button>
            </div>
<!--
          <div class="form-group">
        <label>Quantity: </label>
        <div class="input-group">
            <div class="input-group-btn">
                <button id="down" class="btn btn-default" onclick=" down('0')"><span class="glyphicon glyphicon-minus"></span></button>
            </div>
            <input type="text" id="myNumber" class="form-control input-number" value="0" />
            <div class="input-group-btn">
                <button id="up" class="btn btn-default" onclick="up('10')"><span class="glyphicon glyphicon-plus"></span></button>
            </div>
        </div>
    </div>
 -->
          <% end %>
          <div class="btn btn-default" id="sbtm" data-toggle="modal" data-target='<%= "#detox_description_#{smoothie.id}" %>'>Details</div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
  <% @smoothies.each do |smoothie| %>
  <div class="modal fade" id='<%= "detox_description_#{smoothie.id}" %>' tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header ">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <strong><h4 class="modal-title" id="exampleModalLabel"><%=smoothie.name%></h4></strong>
          <%= smoothie.description %>
        </div>
        <div class="modal-body">
          <div class="smoothie__ingredientss">
            <h2 class="smoothie__ingredients__title">Ingredients</h2>
            <% smoothie.doses.each do |d| %>
            <div class="smoothie-dose__ingredient">
              <div class="smoothie-dose__details">
                <h4 class="ingredient__name">
                  <%= d.ingredient.name %> <%= d.value%><%= d.unit%>
                </h4>
                <div class="ingredient__details">
                  <%= d.ingredient.description || "#{d.ingredient.name} description coming soon..." %>
                </div>
              </div>
              <div class="ingredient__photo">
                <img src="<%= d.ingredient.photo %>" alt="" class="ingredient_photo_popup">
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
       <!--  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
      </div>
    </div>
  </div>
</div>
<% end %>
<script>
// ---------------------------------------------SMOOTHIE QUANTITY BUTTONS
      selectedSmoothieList = document.getElementById(
        'selected-smoothie-list'
        );
const buttonPlus = document.querySelectorAll("button.quantity-increase")
buttonPlus.forEach((button) => {
  button.addEventListener("click", (e) => {
    event.preventDefault();
    increaseQuantity(e.currentTarget)
  })
})
let array = []
function increaseQuantity(target) {
  const id = target.dataset.fieldId
  input = document.getElementById(id)
  input_numeric = Number(input.value)
  input_numeric += 1
  input.value = String(input_numeric)
  total = document.getElementById("selected-smoothies__total").innerText
  total_numeric = Number(total)
  total_numeric += 1
  document.getElementById("selected-smoothies__total").innerText = String(total_numeric)
  smoothie_name = target.parentElement.parentNode.querySelector("h3").innerText
  selectedSmoothieList.querySelectorAll("li").forEach((li) => {
    array.push( li.inneText.substring(li.innerText.indexOf(" ") + 1))
  })
  document.getElementById('selected-smoothie-list').querySelectorAll("li")[0].innerText.substring(document.getElementById('selected-smoothie-list').querySelectorAll("li")[0].innerText.indexOf(" ") + 1)
        listItem = document.createElement('li');
        listItem.className = "list-group-item";
        listItem.innerHTML = `
          <span class="badge">
            ${String(total_numeric)}
          </span>
          ${smoothie_name}
        `;
        selectedSmoothieList.appendChild(listItem);
}
const buttonMinus = document.querySelectorAll("button.quantity-decrease")
buttonMinus.forEach((button) => {
  button.addEventListener("click", (e) => {
    event.preventDefault();
    decreaseQuantity(e.currentTarget)
  })
})
function decreaseQuantity(target) {
  const id = target.dataset.fieldId
  input = document.getElementById(id)
  input_numeric = Number(input.value)
  input_numeric -= 1
  input.value = String(input_numeric)
  total = document.getElementById("selected-smoothies__total").innerText
  total_numeric = Number(total)
  total_numeric -= 1
  document.getElementById("selected-smoothies__total").innerText = String(total_numeric)
}
// ---------------------------BASKET SELECTED SMOOTHIES SIDE BAR:
  const maxSmoothies = <%= raw @order.smoothies_amount.to_json %>;
  const totalSmoothies = <%= raw @smoothies.all().to_json %>;
  const upgradeBanner = document.getElementById('upgrade-banner');
  let selectedSmoothies = {};
  totalSmoothies.forEach((smoothie, index) => {
     totalSelectedSmoothies = document.getElementById(
      'selected-smoothies__total'
      );
     smoothieAmount = document.getElementById(
      `order_order_items_smoothie_quantity${index + 1}`
      );
    smoothieAmount.addEventListener("change", (event) => {
      event.preventDefault();
      (event.target.value === '0')
      ? delete selectedSmoothies[smoothie.name]
      : selectedSmoothies[smoothie.name] = event.target.value;
      while (selectedSmoothieList.firstChild) {
        selectedSmoothieList.removeChild(selectedSmoothieList.firstChild);
      }
      Object.keys(selectedSmoothies).forEach(smoothieName => {
        const listItem = document.createElement('li');
        listItem.className = "list-group-item";
        listItem.innerHTML = `
          <span class="badge">
            ${selectedSmoothies[smoothieName]}
          </span>
          ${smoothieName}
        `;
        selectedSmoothieList.appendChild(listItem);
      });
      const countSelectedSmoothies = Object.values(selectedSmoothies).reduce((total, amount) => parseInt(total) + parseInt(amount));
      totalSelectedSmoothies.innerHTML = countSelectedSmoothies;
      if (countSelectedSmoothies > maxSmoothies) {
        totalSelectedSmoothies.classList.add('text-danger');
        totalSelectedSmoothies.classList.remove('text-success');
        upgradeBanner.classList.remove('hidden');
      } else {
        totalSelectedSmoothies.classList.add('text-success');
        totalSelectedSmoothies.classList.remove('text-danger');
        upgradeBanner.classList.add('hidden');
      }
    });
  });
 // ----------------------------------------------ORDER BUTTON
 document.getElementById("order-submit").addEventListener("click", event => {
    document.querySelector(".simple_form.order").submit()
  })
</script>
<!--
<script type="text/javascript">
function up(max) {
    document.getElementById("myNumber").value = parseInt(document.getElementById("myNumber").value) + 1;
    if (document.getElementById("myNumber").value >= parseInt(max)) {
        document.getElementById("myNumber").value = max;
    }
}
function down(min) {
    document.getElementById("myNumber").value = parseInt(document.getElementById("myNumber").value) - 1;
    if (document.getElementById("myNumber").value <= parseInt(min)) {
        document.getElementById("myNumber").value = min;
    }
}
</script>
 -->

app/views/orders/show.html.erb
<div class="container">
   <h2 class="section__title">Thank you</h2>
  <div class="recap-wrapper">

    <div class=" form recap-box">
      <div class="recap-icon"> <img src="https://res.cloudinary.com/mas-cloud/image/upload/v1544107531/the-smoothie/icon_box_pink-2.png" width="48px" alt="box"> </div>
      <p><strong>Your Smoothies:</strong></p>
      <% @order.order_items.each do |item| %>
        <% next if item.smoothie_quantity == 0 %>
        <% smoothie = Smoothie.find(item.smoothie_id) %>
       <ul>
         <li><%= item.smoothie_quantity %> <%= smoothie.name %></li>
       </ul>
      <% end %>

    </div>
    <div class="form recap-box">
     <div class="recap-icon"><img src="https://res.cloudinary.com/mas-cloud/image/upload/v1544107531/the-smoothie/icon_cycle.png" alt="" width="48px"> <!-- <i class="fas fa-map-marker-alt"> --></i></div>
     <table>
      <tr>
         <td><strong>Will be delivered at:</strong></td>
         <td><%= @order.delivery_address %></td>
      </tr>
      <tr>
        <td><strong>On:</strong></td>
        <td><%= @order.delivery_date.strftime("%B %d, %Y") %></td>
      </tr>
      <tr>
        <td><strong>Time period:</strong></td>
        <td><%= @order.delivery_time_period %></td>
      </tr>
     </table>
   </div>
</div>

  <div class=" recap-bottom col-sm-12">
    <!-- <div class="home-btn">
      <%#= link_to "Home", root_path, class: "btn btn-xs btn-success" %>
    </div> -->
  </div>

</div>