config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  get '/pages/home' => 'pages#home'
  get '/pages/:page' => 'pages#show', as: :page
  get '/preferences' => 'preferences#edit'

  resources :allergies, only: [:new, :create]
  resources :likes, only: [:new, :create]
  resources :dislikes, only: [:new, :create]
  resources :users, only: [:show, :edit, :update]
  resources :orders do
    resources :payments, only: [:new, :create]
  end
  get '/smoothies/:order_id/configure', to: 'orders#configure', as: :order_configure
  post '/orders/:order_id/add_items', to: 'orders#add_items', as: :order_add_items
  get '/orders/:order_id/confirmation', to: 'orders#confirmation', as: :order_confirmation
  post '/orders/:order_id/delivery_info', to: 'orders#delivery_info', as: :order_delivery_info
  get '/smoothies/choose-amount' => 'orders#choose_amount'
  resources :smoothies, only: [:index, :show, :edit, :update]


    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  def edit
    @user = current_user
    @allergies = Allergy.all
    @allergy = Allergy.new
    @dislike = Dislike.new
    @like = Like.new
  end
end

app/views/preferences/edit.html.erb
 <div class="edit-preferences">


  <div class="layout">

    <div class="content">
     <div class="container">
      <h2 class="section__title">Let us know about yourself</h2>

      <div class="preferences-form">
       <% if user_signed_in? %>
       <%= simple_form_for @user do |f| %>

       <strong>
        <div class="value__selected-info-top">
          Age:
        </div>
      </strong>
      <div id="age__selected" class="value__selected">
        23
      </div>
      <%= f.input :age, as: :range, label: false,
      input_html: { id:"age",
        min:18, max:98, step:1, value:30} %>

        <strong><div class="value__selected-info-top">
          Weight:
        </div></strong>
        <div id="weight__selected" class="value__selected">
          56
        </div>
        <%= f.input :weight, as: :range, label: false,
        input_html: { id:"weight",
          min:"30", max:"140", step:"1", value:50} %>

          <strong><div class="value__selected-info-top">
            Height:
          </div></strong>
          <div id="height__selected" class="value__selected">
            174
          </div>
          <%= f.input :height, as: :range, label: false,
          input_html: { id:"height",

            min:"60", max:"220", step:"1", value:160} %>


            <div class="content-bottom">

             <div class="content-bottom-element ">
              <%= f.input :gender, as: :radio_buttons,
              input_html: {class: "form-check-input" },
              collection: [
                ['female', 'Female'],
                ['male', 'Male'],
                ['other', 'Other']
              ],
              selected: 0,
              label_method: :second,
              label_html: {class: "form-check-label"},
              value_method: :first
              %>
            </div>

            <div class="content-bottom-element">
              <%= f.input :goal, as: :radio_buttons,
              input_html: { class: "" },
              collection: [
                ['detox', 'Detox'],
                ['weight-loss', 'Weight Loss'],
                ['muscle', 'Muscle'],
                ['immune', 'Immune'],
                ['energy', 'Energy'],
              ],
              selected: 0,
              label_method: :second
              %>
            </div>
          </div>

          <div class="user-presets">
            <div class="allergies">

              <label class="check_boxes optional form-check-label">Allergies</label>
              <%= f.simple_fields_for @allergy do |al| %>
              <%= al.input :ingredient,
              label: "Allergies",
              collection: [
                ['Flaxseed', 'Soy'],
                ['Spinach', 'Dairy'],
                ['Turmeric', 'Nuts'],
                ['Banana', 'Peanuts'],
                ['Strawberry', 'Flaxseed'],

              ],
              as: :check_boxes,
              label_method: :second,
              value_method: :first
              %>
              <% end %>
              <div class="input-allergies-other">
                <label for="">Other allergies</label>
                <input type="text" class="form-control">
              </div>
            </div>

            <div class="likes">
              <label class="check_boxes optional form-check-label">Likes</label>
              <%= f.simple_fields_for Like.new do |l| %>
              <%= l.input :ingredient,
              label: "Likes",
              collection: [
                ['Strawberry', 'Berries'],
                ['Flaxseed', 'Nuts'],
                ['Spinach', 'Greens'],
                ['Turmeric', 'Spices'],
                ['Banana', 'Banana'],
                ['Avocado', 'Avocado']

              ],
              as: :check_boxes,
              label_method: :second,
              value_method: :first
              %>
              <% end %>
              <div class="input-likes-other">
                <label for="">Other likes</label>
                <input type="text" class="form-control">
              </div>
            </div>

            <div class="dislikes">
              <label class="check_boxes optional form-check-label">Dislikes</label>
              <%= f.simple_fields_for Dislike.new do |di| %>
              <%= di.input :ingredient,
              label: "Dislikes",
              collection: [
                ['Strawberry', 'Berries'],
                ['Flaxseed', 'Nuts'],
                ['Spinach', 'Greens'],
                ['Turmeric', 'Spices'],
                ['Banana', 'Banana'],
                ['Avocado', 'Avocado']
              ],
              as: :check_boxes,
              label_method: :second,
              value_method: :first
              %>
              <% end %>
              <div class="input-dislikes-other">
                <label for="">Other dislikes</label>
                <input type="text" class="form-control">
              </div>

            </div>
          </div>
          <%= f.submit 'Done', class: 'testbtn btn btn-lg btn-success' %>
        </div>
        <% end %>
      </div>
    </div>

    <% else %>
    <h1>Hi Guest!</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias eum, maxime vel soluta.</p>
    <!-- Create a new user instance -->
    <%= link_to 'Configure', smoothies_configure_path, class: "btn btn-default" %>
    <% end %>

    <script>

  // document.querySelector(".testbtn").addEventListener("click", event => {
  //   console.log("hello")
  //   document.querySelectorAll("form").forEach(form => {
  //     form.submit()
  //   })
  // })

  const age = document.getElementById("age");
  const selected_age = document.getElementById("age__selected");
  age.addEventListener("change", (event) => {
    event.preventDefault();
    selected_age.innerHTML = event.target.value;

  });
  const weight = document.getElementById("weight");
  const selected_weight = document.getElementById("weight__selected");
  weight.addEventListener("change", (event) => {
    event.preventDefault();
    selected_weight.innerHTML = event.target.value;

  });
  const height = document.getElementById("height");
  const selected_height = document.getElementById("height__selected");
  height.addEventListener("change", (event) => {
    event.preventDefault();
    selected_height.innerHTML = event.target.value;

  });


</script>

</div>