config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  get '/pages/home' => 'pages#home'
  get '/pages/:page' => 'pages#show', as: :page
  get '/preferences' => 'preferences#edit'

  resources :allergies, only: [:new, :create]
  resources :likes, only: [:new, :create]
  resources :dislikes, only: [:new, :create]
  resources :users, only: [:show, :edit, :update]
  resources :orders do
    resources :payments, only: [:new, :create]
  end
  get '/smoothies/:order_id/configure', to: 'orders#configure', as: :order_configure
  post '/orders/:order_id/add_items', to: 'orders#add_items', as: :order_add_items
  get '/orders/:order_id/confirmation', to: 'orders#confirmation', as: :order_confirmation
  post '/orders/:order_id/delivery_info', to: 'orders#delivery_info', as: :order_delivery_info
  get '/smoothies/choose-amount' => 'orders#choose_amount'
  resources :smoothies, only: [:index, :show, :edit, :update]


    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/smoothies_controller.rb
class SmoothiesController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @smoothies = Smoothie.all
  end

  def show
    @smoothie = Smoothie.find(params[:id])
  end
end

app/views/smoothies/_smoothie.html.erb
<div class="smoothie">
  <div>
    <img src="<%= s.photo %>" alt="" width ="160" height="160">
  </div>
  <h3><%= s.name %></h3>
  <p><%= s.description %></p>
  <%= link_to 'Details', smoothy_path(s), class: "btn btn-default" %>
</div>

app/views/smoothies/configure.html.erb
<div class="container">
  <h2 class="section__title">Configure Your Basket</h2>

  <div class="smoothies">
    <% @smoothies.each do |s| %>
    <div class="smoothie">
      <img src="https://res.cloudinary.com/mas-cloud/image/upload/v1543489199/the-smoothie/smoothie-green.png" alt="" width ="150" height="120">
      <h3><%=s.name%></h3>
      <div class="smoothie__amount">
        <div class="smoothie__remove btn btn-default">
          -
        </div>
        <div class="smoothie__count">
          1
        </div>
        <div class="add btn btn-default">
          +
        </div>
      </div>
      <div class="btn btn-default">Details</div> <!--Will Open the modal-->
    </div>
    <% end %>
  </div>
  <%= link_to 'Order', page_path("order"), class: "btn btn-lg btn-center btn-success" %>

</div>

app/views/smoothies/index.html.erb
<div class="container">
  <div class="smoothies">
    <% @smoothies.each do |s| %>
      <div>
        <%= render 'smoothie', { s: s } %>
      </div>
    <% end %>
  </div>
  <div class="btn btn-center">  <%= link_to 'Get Started', page_path("choose-amount"), class: "btn btn-lg btn-success b1" %>
  </div>
</div>

app/views/smoothies/show.html.erb
<div class="container">
  <div class="smoothie--detail">
    <div>
      <img src="<%= @smoothie.photo %>" alt="" width ="400" height="400">
    </div>
    <h1><%= @smoothie.name %></h1>
    <p><%= @smoothie.nickname %></p>
    <p><%= @smoothie.description %></p>

    <div class="smoothie__ingredients">
      <h2 class="smoothie__ingredients__title">Ingredients:</h2>
      <% @smoothie.doses.each do |d| %>
        <div class="smoothie__ingredient">
          <%= d.ingredient.name %> <%= d.value%><%= d.unit%>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row btn-lg btn-center">
   <div class="col-sm-6"> <%= link_to 'Back', smoothies_path, class: 'btn btn-lg btn-center btn-success' %> </div>
   <div class="col-sm-6"><%= link_to 'Order', page_path("choose-amount"), class: 'btn btn-lg btn-center btn-success' %></div>
  </div>
</div>