config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'pages#home'
  get '/pages/home' => 'pages#home'
  get '/pages/:page' => 'pages#show', as: :page
  get '/preferences' => 'preferences#edit'

  resources :allergies, only: [:new, :create]
  resources :likes, only: [:new, :create]
  resources :dislikes, only: [:new, :create]
  resources :users, only: [:show, :edit, :update]
  resources :orders do
    resources :payments, only: [:new, :create]
  end
  get '/smoothies/:order_id/configure', to: 'orders#configure', as: :order_configure
  post '/orders/:order_id/add_items', to: 'orders#add_items', as: :order_add_items
  get '/orders/:order_id/confirmation', to: 'orders#confirmation', as: :order_confirmation
  post '/orders/:order_id/delivery_info', to: 'orders#delivery_info', as: :order_delivery_info
  get '/smoothies/choose-amount' => 'orders#choose_amount'
  resources :smoothies, only: [:index, :show, :edit, :update]


    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order
def new
  @order = Order.find(params[:id])
end

def create
  customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
  )

  charge = Stripe::Charge.create(
    customer:     customer.id,  # You should store this customer id and re-use it.
    amount:       @order.total_smoothies_price_cents,
    description:  "Payment for #{@order.smoothies_amount} smoothies for order #{@order.id}",
    currency:     @order.total_smoothies_price.currency
  )

  @order.update(payment: charge.to_json, payed: true)
  redirect_to order_path(@order)
rescue Stripe::CardError => e
  flash[:alert] = e.message
  redirect_to new_order_payment_path(@order)
end

private

  def set_order
    @order = current_user.orders.where(payed: false).find(params[:order_id])
  end
end

app/views/payments/_new.html.erb
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@order.total_smoothies_price) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My Smoothies"
    data-email="<%= current_user.email %>"
    data-description="<%= @order.smoothies_amount %> smoothies <%= humanized_money_with_symbol(@order.total_smoothies_price) %>"
    data-amount="<%= @order.total_smoothies_price_cents %>">
  </script>

<% end %>

app/views/payments/new.html.erb
<h1>Purchase of Smoothies</h1>
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@order.total_smoothies_price) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My Smoothies"
    data-email="<%= current_user.email %>"
    data-description="<%= @order.smoothies_amount %> smoothies <%= humanized_money_with_symbol(@order.total_smoothies_price) %>"
    data-amount="<%= @order.total_smoothies_price %>"
  </script>

<% end %>